### ISSUE TITLE
Increment minor version on breaking jandex changes

### ISSUE THREAD

**Issue by creckord** [wildfly/jandex-maven-plugin#21]
jandex-maven-plugin 1.0.6 included a breaking change due to its [update of the jandex version from 2.0.3 to 2.1.1](https://github.com/wildfly/jandex-maven-plugin/commit/feb6096fefec210a881a442cff0ecf1938ae9d52). Jandex 2.1.1 uses a newer index format (version 9) than 2.0.3 (version 6) and the index files written by it cannot be read with the older jandex version.

I think in such cases the maven plugin should be more explicit about the breaking change by increasing its minor version (i.e. it should have gone from 1.0.5 to 1.1.0 at the time).

I don't think that anything useful can be done about this retroactively now, but it would be great if this could be considered for future updates. 

I would suggest adding a unit test that checks for the written index version against a current expected value.

**Comment by famod** [comment]
Following your good suggestion, #24 will bump to 1.1.0 (if it is merged by one of the maintainers).
