### ISSUE TITLE
UnsupportedVersion after using Jandex Maven Plugin 1.2.0

### ISSUE THREAD

**Issue by Flurb** [wildfly/jandex-maven-plugin#34]
For our Quarkus microservice, we upgraded the Jandex Maven Plugin from 1.1.1 to 1.2.0.
During the build, it gives an UnsupportedVersion

> Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: org.jboss.jandex.UnsupportedVersion: Version: 10

Full error message:
> Failed to execute goal io.quarkus:quarkus-maven-plugin:2.2.1.Final:build (default) on project app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: org.jboss.jandex.UnsupportedVersion: Version: 10
[ERROR]         at org.jboss.jandex.IndexReader.initReader(IndexReader.java:87)
[ERROR]         at org.jboss.jandex.IndexReader.readVersion(IndexReader.java:137)
[ERROR]         at org.jboss.jandex.IndexReader.getIndexVersion(IndexReader.java:124)
[ERROR]         at io.quarkus.deployment.index.IndexingUtil.indexJar(IndexingUtil.java:58)
[ERROR]         at io.quarkus.deployment.index.IndexingUtil.indexJar(IndexingUtil.java:49)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep$1.apply(ApplicationArchiveBuildStep.java:287)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep$1.apply(ApplicationArchiveBuildStep.java:283)
[ERROR]         at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep.handleJarPath(ApplicationArchiveBuildStep.java:283)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep.indexPath(ApplicationArchiveBuildStep.java:192)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep.addMarkerFilePaths(ApplicationArchiveBuildStep.java:236)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep.scanForOtherIndexes(ApplicationArchiveBuildStep.java:125)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep.build(ApplicationArchiveBuildStep.java:103)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

Do we need to upgrade something else in order to use 1.2.0 instead of 1.1.1?

**Comment by Ladicek** [comment]
Jandex Maven plugin 1.2.0 uses Jandex 2.4.0.Final, which produces newer index format. Quarkus 2.2 uses Jandex 2.3.1.Final, which can't read the new index format. The recommendation would be to not update to Jandex Maven plugin 1.2.0 with Quarkus 2.2 or earlier.

Jandex unfortunately didn't have a written compatibility promise before, I added one here: https://github.com/wildfly/jandex/pull/136 Also unfortunately, the Jandex version and Jandex Maven plugin version are detached -- that should be addressed in Jandex 3.0, where they will both be released together.
