### ISSUE TITLE
Make plugin work with Java 8

### ISSUE THREAD

**Issue by malamut2** [wildfly/jandex-maven-plugin#7]
The plugin contains a dependency to an old jandex version, which is not fully Java 8 compliant (in my specifiy case, I run into 'unknown tag'). This can be worked around by users by adding a dependency to jandex 2.0.0.Final to the plugin, but it would be nicer to have it in the original plugin POM.

**Comment by heiko-braun** [comment]
This is covered by PR #9

**Comment by heiko-braun** [comment]
The above PR move it to 2.0.1.Final, which is the version included with WildFly 10
